### ISSUE TITLE
Fabric 1.18.2 Support?

### ISSUE THREAD

**Issue by StickyChannel92** [imkonni/instant-blocks#2]
I have fabric, and most of my mods don't have a forge port. Do you have any chance to make a 1.18.2 Fabric port of this mod?

**Comment by imkonni** [comment]
Fabric support added in [1.19-1.6.1](https://github.com/slymask3/instant-blocks/releases/tag/1.19-1.6.1) and [1.18.2-1.6.1](https://github.com/slymask3/instant-blocks/releases/tag/1.18.2-1.6.1)

[https://www.curseforge.com/minecraft/mc-mods/instant-blocks-fabric](https://www.curseforge.com/minecraft/mc-mods/instant-blocks-fabric)
