### ISSUE TITLE
Statues don't look correct.

### ISSUE THREAD

**Issue by ZaneFlynt01** [imkonni/instant-blocks#4]
All the parts of a Player Statue generated from the Statue block are mirrored. And, not mirrored as in you take a screenshot of the skin as a model from something like Skindex or something and then mirror it, but EVERYTHING is mirrored, which for some skins makes them look completely wrong.

I have a skin that has me wearing a Mage robe. It's got a small amount of the robe open on the front, and it's opened through the center of the skin.

![2022-08-16_17 20 46](https://user-images.githubusercontent.com/71738041/184987782-145cf537-972e-47e7-93ad-9a84c38baf55.png)

However, the statue makes it so the legs are pretty much just a large flap that goes down my legs. It's inconsistent, too, seeing as the sides of my legs are not like that.

**Comment by imkonni** [comment]
Testing with a skin template now - you're absolutely right, thanks for the find! I'll have it fixed for next release.
