### ISSUE TITLE
states using rgb mode blurry

### ISSUE THREAD

**Issue by GrenFlem** [imkonni/instant-blocks#6]
any rgb mode statue is blurry
![image_2022-09-27_032658346](https://user-images.githubusercontent.com/108261952/192502163-280506b0-6115-4e16-b56a-fe744212a3e1.png)

**Comment by GrenFlem** [comment]
its sodium incompatibility, biome blend, please fix, optifine biome blend options dont affect the statues, but on sodium they do

**Comment by imkonni** [comment]
This is a known issue in Sodium [#895](https://github.com/CaffeineMC/sodium-fabric/issues/895) - a solution for this will be implemented in Sodium 0.5 from what I understand. In the meantime you could download the [Unofficial Sodium Biome Blending Fix](https://modrinth.com/mod/unofficial-sodium-biome-blending-fix).
